#!/bin/sh

DOTFILES_DIR="$HOME/dotfiles"

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\\n$fmt\\n" "$@"
}

# shellcheck disable=SC2154
trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e

SYMLINKS_DIR=$HOME/dotfiles/symlinks

files=(
"aliases"
"better-commits.json"
"gitconfig"
"gitignore_global"
"hgrc"
"hushlogin"
"zprofile"
"zshenv"
"zshrc"
)

fancy_echo "Creating symlinks ..."

for file in "${files[@]}"; do
  if [ -f "$HOME"/."$file" ]; then
    fancy_echo ".$file already present. Backing up..."
    rm -f "$HOME"/."$file"
  fi
  fancy_echo "-> Linking $SYMLINKS_DIR/$file to $HOME/.$file..."
  ln -s "$SYMLINKS_DIR"/"$file" "$HOME"/."$file"
done

fancy_echo "Creating directories ..."

if [ ! -d "$HOME/.composer/" ]; then
  mkdir "$HOME/.composer"
fi

if [ ! -d "$HOME/.nvm/" ]; then
  mkdir "$HOME/.nvm"
fi

if [ ! -d "$HOME/.bin/" ]; then
  mkdir "$HOME/.bin"
fi

if [ ! -d "$HOME/github/" ]; then
  mkdir "$HOME/github"
fi
