# Load main files
source ~/.aliases
source ~/dotfiles/shell/functions

# History settings
setopt hist_ignore_all_dups inc_append_history
HISTFILE=~/.zhistory
HISTSIZE=4096
SAVEHIST=4096

# Paths

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  /usr/local/opt/ruby/bin
  /usr/local/share/npm/bin
  /usr/{bin,sbin}
  /{bin,sbin}
  $path
)

# recommended by brew doctor
export PATH="$PATH:/usr/local/bin:$PATH"

export PATH="$PATH:/Users/thatryan/.composer/vendor/bin"

export PATH="/Users/$(whoami)/code/dealerinspire/feature-dev-shared-scripts/devtools-cli:$PATH"

export NVM_DIR="/Users/thatryan/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

